### ISSUE TITLE
CocoaPods 1.0

### ISSUE THREAD

**Issue by banjun** [mzp/cocoapods-app_group#1]
Podfile structure has been changed

**Comment by banjun** [comment]
actually Podfile can be edited to work with `cocoapods-app_group` on current version.
https://github.com/codefirst/AsakusaSatellite-ios/commit/1d2e724d153a7e83112d89ec4e18b3a35c8377c0#diff-4a25b996826623c4a3a4910f47f10c30

**Comment by banjun** [comment]
cannot work with nested targets

**Comment by mzp** [comment]
did it https://github.com/mzp/cocoapods-app_group/commit/a2ea88701c4bad1c92651ff5aab166ccca7bddd5
